// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zybyhasqccenawncazyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5YnloYXNxY2NlbmF3bmNhenlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTg3MjAsImV4cCI6MjA3NDQzNDcyMH0.LUpEgquQILVAIOhnD2htihgpFmyEkVj7r6vLB8DxmT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});